pipeline {
    agent any
    environment {
      REGISTRY="docker.io"
      REPOSITORY="courselabs"
      IMAGE_TAG="${REGISTRY}/${REPOSITORY}/multi-stage:${BUILD_NUMBER}"
    }
    stages {
        stage('Audit tools') {                        
            steps {
                sh 'docker version'
            }
        }
        stage('Build') {
            steps {
              echo "Building Java image"
              dir ('labs/pipeline') {
                sh '''
                  docker build -t ${IMAGE_TAG} -f multi-stage/Dockerfile .
                '''
              }
            }
        }
        stage('Test') {
          steps {
              echo "Running Java container"
              sh '''
                docker run ${IMAGE_TAG}
              '''
            }
        }
    }
}