# Alpine is a tiny Linux distro
FROM alpine

# apk is the package manager for Alpine
# this installs curl into the container image
RUN apk add curl

# tells Docker to run curl when it starts a container
CMD curl