FROM courselabs/java:jdk-21.12 AS builder

WORKDIR /src
COPY HelloWorld.java .

RUN mkdir -p /out/bin && \
    javac -d /out/bin HelloWorld.java

# app image
FROM courselabs/java:jre-21.12 

WORKDIR /app
COPY --from=builder /out/bin/HelloWorld.class .

CMD java HelloWorld